services:
  app:
    image: bloglist-front
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:80
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:4000/
    container_name: bloglist-front

  mongo:
    image: mongo
    ports:
      - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./backend/utils/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./backend/mongo_data:/data/db

  server:
    image: bloglist-back
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/usr/src/app
    ports:
      - 4000:4000
    environment:
      - MONGODB_URI=mongodb://the_username:the_password@mongo:27017/the_database
      - PORT=4000
    container_name: bloglist-back
    depends_on:
      - mongo

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - app # wait for the frontend container to be started
      - server